/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param visible 
 * @param billable 
 * @param parentTitle 
 * @param project 
 * @param id 
 * @param comment 
 * @param metaFields 
 * @param teams 
 * @param color 
 */
@Serializable

data class ActivityCollection (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "visible") @Required val visible: kotlin.Boolean,

    @SerialName(value = "billable") @Required val billable: kotlin.Boolean,

    @SerialName(value = "parentTitle") val parentTitle: kotlin.String? = null,

    @SerialName(value = "project") val project: kotlin.Int? = null,

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "metaFields") val metaFields: kotlin.collections.List<ActivityMeta>? = null,

    @SerialName(value = "teams") val teams: kotlin.collections.List<Team>? = null,

    @SerialName(value = "color") val color: kotlin.String? = null

)

