/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param rate The rate (eg. 10.5)
 * @param user User ID
 * @param internalRate The internal rate (eg. 10.0 or 10)
 * @param isFixed 
 */
@Serializable

data class ActivityRateForm (

    /* The rate (eg. 10.5) */
    @SerialName(value = "rate") @Required val rate: kotlin.Double,

    /* User ID */
    @SerialName(value = "user") val user: kotlin.Int? = null,

    /* The internal rate (eg. 10.0 or 10) */
    @SerialName(value = "internalRate") val internalRate: kotlin.Double? = null,

    @SerialName(value = "isFixed") val isFixed: kotlin.Boolean? = null

)

