/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param comment 
 * @param invoiceText 
 * @param project Project ID
 * @param teams Team ID
 * @param color The hexadecimal color code (default: #d2d6de)
 * @param visible 
 * @param billable 
 */
@Serializable

data class ActivityEditForm (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "invoiceText") val invoiceText: kotlin.String? = null,

    /* Project ID */
    @SerialName(value = "project") val project: kotlin.Int? = null,

    /* Team ID */
    @SerialName(value = "teams") val teams: kotlin.Int? = null,

    /* The hexadecimal color code (default: #d2d6de) */
    @SerialName(value = "color") val color: kotlin.String? = null,

    @SerialName(value = "visible") val visible: kotlin.Boolean? = null,

    @SerialName(value = "billable") val billable: kotlin.Boolean? = null

)

