/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param visible 
 * @param billable 
 * @param country 
 * @param currency 
 * @param timezone 
 * @param budget 
 * @param timeBudget 
 * @param id 
 * @param number 
 * @param comment 
 * @param company 
 * @param vatId 
 * @param contact 
 * @param address 
 * @param phone 
 * @param fax 
 * @param mobile 
 * @param email 
 * @param homepage 
 * @param metaFields 
 * @param teams 
 * @param budgetType 
 * @param color 
 */
@Serializable

data class CustomerEntity (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "visible") @Required val visible: kotlin.Boolean,

    @SerialName(value = "billable") @Required val billable: kotlin.Boolean,

    @SerialName(value = "country") @Required val country: kotlin.String,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "timezone") @Required val timezone: kotlin.String,

    @SerialName(value = "budget") @Required val budget: kotlin.Float,

    @SerialName(value = "timeBudget") @Required val timeBudget: kotlin.Int,

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "number") val number: kotlin.String? = null,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "company") val company: kotlin.String? = null,

    @SerialName(value = "vatId") val vatId: kotlin.String? = null,

    @SerialName(value = "contact") val contact: kotlin.String? = null,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "fax") val fax: kotlin.String? = null,

    @SerialName(value = "mobile") val mobile: kotlin.String? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "homepage") val homepage: kotlin.String? = null,

    @SerialName(value = "metaFields") val metaFields: kotlin.collections.List<CustomerMeta>? = null,

    @SerialName(value = "teams") val teams: kotlin.collections.List<Team>? = null,

    @SerialName(value = "budgetType") val budgetType: kotlin.String? = null,

    @SerialName(value = "color") val color: kotlin.String? = null

)

