/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param country 
 * @param currency 
 * @param timezone 
 * @param number 
 * @param comment 
 * @param company 
 * @param vatId 
 * @param contact 
 * @param address 
 * @param phone 
 * @param fax 
 * @param mobile 
 * @param email 
 * @param homepage 
 * @param invoiceText 
 * @param invoiceTemplate 
 * @param color The hexadecimal color code (default: #d2d6de)
 * @param visible 
 * @param billable 
 */
@Serializable

data class CustomerEditForm (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "country") @Required val country: kotlin.String,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    @SerialName(value = "timezone") @Required val timezone: kotlin.String,

    @SerialName(value = "number") val number: kotlin.String? = null,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "company") val company: kotlin.String? = null,

    @SerialName(value = "vatId") val vatId: kotlin.String? = null,

    @SerialName(value = "contact") val contact: kotlin.String? = null,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "fax") val fax: kotlin.String? = null,

    @SerialName(value = "mobile") val mobile: kotlin.String? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "homepage") val homepage: kotlin.String? = null,

    @SerialName(value = "invoiceText") val invoiceText: kotlin.String? = null,

    @SerialName(value = "invoiceTemplate") val invoiceTemplate: kotlin.String? = null,

    /* The hexadecimal color code (default: #d2d6de) */
    @SerialName(value = "color") val color: kotlin.String? = null,

    @SerialName(value = "visible") val visible: kotlin.Boolean? = null,

    @SerialName(value = "billable") val billable: kotlin.Boolean? = null

)

