/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param copy 
 * @param begin 
 */
@Serializable

data class GetRestartTimesheetGetRequest (

    @SerialName(value = "copy") val copy: kotlin.String? = null,

    @SerialName(value = "begin") val begin: kotlin.String? = null

)

