/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param title 
 * @param url 
 * @param propertyClass 
 * @param attr 
 * @param divider 
 */
@Serializable

data class PageAction (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "url") val url: kotlin.String? = null,

    @SerialName(value = "class") val propertyClass: kotlin.String? = null,

    @SerialName(value = "attr") val attr: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "divider") val divider: kotlin.Boolean? = null

)

