/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param version 
 */
@Serializable

data class Plugin (

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "version") val version: kotlin.String? = null

)

