/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param `value` ATTENTION: This field can be used to temporary hold data in another format (e.g. array) during form transformation,
 */
@Serializable

data class ProjectMeta (

    @SerialName(value = "name") @Required val name: kotlin.String,

    /* ATTENTION: This field can be used to temporary hold data in another format (e.g. array) during form transformation, */
    @SerialName(value = "value") val `value`: kotlin.String? = null

)

