/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param name The tag name (forbidden character: comma)
 * @param color The hexadecimal color code (default: #d2d6de)
 * @param visible 
 */
@Serializable

data class TagEditForm (

    /* The tag name (forbidden character: comma) */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The hexadecimal color code (default: #d2d6de) */
    @SerialName(value = "color") val color: kotlin.String? = null,

    @SerialName(value = "visible") val visible: kotlin.Boolean? = null

)

