/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param name Name of the team
 * @param members All team members
 * @param color The hexadecimal color code (default: #d2d6de)
 */
@Serializable

data class TeamEditForm (

    /* Name of the team */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* All team members */
    @SerialName(value = "members") @Required val members: kotlin.collections.List<TeamEditFormMembersInner>,

    /* The hexadecimal color code (default: #d2d6de) */
    @SerialName(value = "color") val color: kotlin.String? = null

)

