/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param id 
 * @param members 
 * @param customers 
 * @param projects 
 * @param activities 
 * @param color 
 */
@Serializable

data class Team (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "members") val members: kotlin.collections.List<TeamMember>? = null,

    @SerialName(value = "customers") val customers: kotlin.collections.List<Customer>? = null,

    @SerialName(value = "projects") val projects: kotlin.collections.List<Project>? = null,

    @SerialName(value = "activities") val activities: kotlin.collections.List<Activity>? = null,

    @SerialName(value = "color") val color: kotlin.String? = null

)

