/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param name 
 * @param id 
 * @param color 
 */
@Serializable

data class TeamCollection (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "color") val color: kotlin.String? = null

)

