/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param team 
 * @param teamlead 
 */
@Serializable

data class TeamMembership (

    @SerialName(value = "team") @Required val team: Team,

    @SerialName(value = "teamlead") @Required val teamlead: kotlin.Boolean

)

