/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 *
 *
 * @param trackingMode
 * @param defaultBeginTime
 * @param activeEntriesHardLimit
 * @param isAllowFutureTimes
 * @param isAllowOverlapping
 */
@Serializable

data class TimesheetConfig (

    @SerialName(value = "trackingMode") val trackingMode: kotlin.String? = null,

    @SerialName(value = "defaultBeginTime") val defaultBeginTime: kotlin.String? = null,

    @SerialName(value = "activeEntriesHardLimit") val activeEntriesHardLimit: kotlin.Int? = null,

    @SerialName(value = "isAllowFutureTimes") val isAllowFutureTimes: kotlin.Boolean? = null,

    @SerialName(value = "isAllowOverlapping") val isAllowOverlapping: kotlin.Boolean? = null

)

