/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param begin Attention: Accessor MUST be used, otherwise date will be serialized in UTC.
 * @param exported 
 * @param billable 
 * @param activity 
 * @param project 
 * @param user 
 * @param tags 
 * @param id 
 * @param end Attention: Accessor MUST be used, otherwise date will be serialized in UTC.
 * @param duration 
 * @param description 
 * @param rate 
 * @param internalRate 
 * @param fixedRate 
 * @param hourlyRate 
 * @param metaFields 
 */
@Serializable

data class TimesheetEntity (

    /* Attention: Accessor MUST be used, otherwise date will be serialized in UTC. */
    @SerialName(value = "begin") @Required val begin: kotlin.String,

    @SerialName(value = "exported") @Required val exported: kotlin.Boolean,

    @SerialName(value = "billable") @Required val billable: kotlin.Boolean,

    @SerialName(value = "activity") val activity: kotlin.Int? = null,

    @SerialName(value = "project") val project: kotlin.Int? = null,

    @SerialName(value = "user") val user: kotlin.Int? = null,

    @SerialName(value = "tags") val tags: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "id") val id: kotlin.Int? = null,

    /* Attention: Accessor MUST be used, otherwise date will be serialized in UTC. */
    @SerialName(value = "end") val end: kotlin.String? = null,

    @SerialName(value = "duration") val duration: kotlin.Int? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "rate") val rate: kotlin.Float? = null,

    @SerialName(value = "internalRate") val internalRate: kotlin.Float? = null,

    @SerialName(value = "fixedRate") val fixedRate: kotlin.Float? = null,

    @SerialName(value = "hourlyRate") val hourlyRate: kotlin.Float? = null,

    @SerialName(value = "metaFields") val metaFields: kotlin.collections.List<TimesheetMeta>? = null

)

