/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param begin 
 * @param project Project ID
 * @param activity Activity ID
 * @param end 
 * @param description 
 * @param fixedRate Fixed rate
 * @param hourlyRate Hourly rate
 * @param user User ID
 * @param tags Comma separated list of tags
 * @param exported 
 * @param billable 
 */
@Serializable

data class TimesheetEditForm (

    @SerialName(value = "begin") @Required val begin: kotlin.String,

    /* Project ID */
    @SerialName(value = "project") @Required val project: kotlin.Int,

    /* Activity ID */
    @SerialName(value = "activity") @Required val activity: kotlin.Int,

    @SerialName(value = "end") val end: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    /* Fixed rate */
    @SerialName(value = "fixedRate") val fixedRate: kotlin.Double? = null,

    /* Hourly rate */
    @SerialName(value = "hourlyRate") val hourlyRate: kotlin.Double? = null,

    /* User ID */
    @SerialName(value = "user") val user: kotlin.Int? = null,

    /* Comma separated list of tags */
    @SerialName(value = "tags") val tags: kotlin.String? = null,

    @SerialName(value = "exported") val exported: kotlin.Boolean? = null,

    @SerialName(value = "billable") val billable: kotlin.Boolean? = null

)

