/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param memberships 
 * @param username 
 * @param preferences 
 * @param language 
 * @param timezone 
 * @param teams 
 * @param initials 
 * @param id 
 * @param alias 
 * @param title 
 * @param avatar 
 * @param accountNumber 
 * @param enabled 
 * @param roles 
 * @param color 
 */
@Serializable

data class UserEntity (

    @SerialName(value = "memberships") @Required val memberships: kotlin.collections.List<TeamMembership>,

    @SerialName(value = "username") @Required val username: kotlin.String,

    @SerialName(value = "preferences") val preferences: kotlin.collections.List<UserPreference>? = null,

    @SerialName(value = "language") val language: kotlin.String? = null,

    @SerialName(value = "timezone") val timezone: kotlin.String? = null,

    @SerialName(value = "teams") val teams: kotlin.collections.List<Team>? = null,

    @SerialName(value = "initials") val initials: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "alias") val alias: kotlin.String? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "avatar") val avatar: kotlin.String? = null,

    @SerialName(value = "accountNumber") val accountNumber: kotlin.String? = null,

    @SerialName(value = "enabled") val enabled: kotlin.Boolean? = null,

    @SerialName(value = "roles") val roles: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "color") val color: kotlin.String? = null

)

