/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.progeek.kimai.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param version 
 * @param versionId Follows the same logic as PHP_VERSION_ID, see https://www.php.net/manual/de/function.phpversion.php
 * @param copyright 
 */
@Serializable

data class Version (

    @SerialName(value = "version") val version: kotlin.String? = null,

    /* Follows the same logic as PHP_VERSION_ID, see https://www.php.net/manual/de/function.phpversion.php */
    @SerialName(value = "versionId") val versionId: kotlin.Int? = null,

    @SerialName(value = "copyright") val copyright: kotlin.String? = null

)

